codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**/*.freezed.dart"
  - "**/*.g.dart"
  - "examples/"
  - "packages/flusmic/lib/src/models"
  - "packages/flusmic/test/.test_coverage.dart"