targets:
  $default:
    builders:
      json_serializable:
          options:
            any_map: true
            checked: true
            explicit_to_json: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - non_constant_identifier_names
            - unused_element